$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
parameters:
  Token:
    type: string
    defaultValue: PAT-Token
resources:
- name: Working with classic DSC resources for ADO v4
  type: Microsoft.Windows/WindowsPowerShell
  properties:
    resources:
    - name: Create ADO project - DSC
      type: AzureDevOpsDscv3/ProjectResource
      properties:
        Organization: ExampleOrganization
        ProjectName: TestDSC
        Description: "Project created via DSC v3 with secure parameters"
        pat: "[parameters('Token')]"
        SourceControlType: Git
        Ensure: Present
    - name: AddUser
      type: AzureDevOpsDscv3/OrganizationUserResource
      properties:
        UserPrincipalName: UserPrincipalName
        Organization: ExampleOrganization
        AccessLevel: Basic  # or Stakeholder, BasicPlusTestPlans
        Ensure: Present
        pat: "[parameters('Token')]"
    - name: AddGroup
      type: AzureDevOpsDscv3/OrganizationGroupResource
      properties:
        GroupOriginId: EntraID-GroupObjectID   # group descriptor
        GroupDisplayName: EntraID-GroupDisplayName
        Organization: ExampleOrganization
        AccessLevel: Basic
        Ensure: Present
        pat: "[parameters('Token')]"
    - name: AddPermissionProject
      type: AzureDevOpsDscv3/ProjectUserPermissionResource
      properties:
        ProjectName: TestDSCv11
        PermissionLevel: ProjectAdministrators  # ProjectAdministrators, ProjectValidUsers, Readers, or ReleaseAdministrators.
        UserPrincipalName: UserPrincipalName
        Organization: ExampleOrganization
        Ensure: Absent
        pat: "[parameters('Token')]"
    - name: AddPermissionProject
      type: AzureDevOpsDscv3/ProjectGroupPermissionResource
      properties:
        ProjectName: TestDSCv11
        PermissionLevel: ProjectAdministrators  # ProjectAdministrators, ProjectValidUsers, Readers, or ReleaseAdministrators.
        GroupDisplayName: EntraID-GroupDisplayName
        GroupOriginId: EntraID-GroupObjectID   # group descriptor
        Organization: ExampleOrganization
        Ensure: Absent
        pat: "[parameters('Token')]"